framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: { enabled: true }
    validation: { enable_annotations: true }
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true

    cache:
        default_redis_provider: 'redis://%app.redis.host%:%app.redis.port%/cache'
        app: cache.adapter.redis
