framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: { enabled: true }
    validation: { enable_annotations: true }
    #http_method_override: true

    # uncomment this entire section to enable sessions
    session: ~

    #esi: ~
    #fragments: ~
    php_errors:
        log: true
        
    cache:
        pools:
            cache.annotations:
                adapter: cache.adapter.redis
                default_lifetime: 3600
