security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        allow_anonymous:
            pattern: ^/login
            anonymous: ~
        pre_production:
            host: ^(preprod|staging|dev)\.villadbay\.com$
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            logout:
                path: app_logout
                success_handler: 'App\Security\LogoutSuccessHandler'
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            logout:
                path: app_logout
                success_handler: 'App\Security\LogoutSuccessHandler'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    access_control:
        # require ROLE_SUPERADMIN for dev domain
        - { path: ^/, roles: ROLE_SUPERADMIN, host: ^dev\.villadbay\.com$, allow_if: "request.getPathInfo() matches '#^/login#' or request.getPathInfo() matches '#^/logout$#'" }
        # require ROLE_ADMIN for staging and preprod domain
        - { path: ^/, roles: ROLE_ADMIN, host: ^staging\.villadbay\.com$, allow_if: "request.getPathInfo() matches '#^/login#' or request.getPathInfo() matches '#^/logout$#'" }
        - { path: ^/, roles: ROLE_ADMIN, host: ^preprod\.villadbay\.com$, allow_if: "request.getPathInfo() matches '#^/login#' or request.getPathInfo() matches '#^/logout$#'" }
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN, allow_if: "request.getPathInfo() matches '#^/admin/login#'" }

    role_hierarchy:
        ROLE_USER: ROLE_GUEST
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERADMIN: ROLE_ADMIN

